/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kma.bookmanangement.ui;


import java.awt.event.KeyEvent;

import com.kma.bookmanangement.controller.EnterBookController;

/**
 *
 * @author lxsgo
 */
public class EnterBookForm extends javax.swing.JFrame {

    /**
     * Creates new form EnterBookForm
     */
    public EnterBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookIdInputField = new javax.swing.JTextField();
        titleInputField = new javax.swing.JTextField();
        authorInputField = new javax.swing.JTextField();
        publicDateInputField = new javax.swing.JTextField();
        categoryInputField = new javax.swing.JTextField();
        bookIdLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        publicDateLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        enterBookButton = new javax.swing.JButton();
        saveBookButton = new javax.swing.JButton();
        closeFormButton = new javax.swing.JButton();
        messageField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookIdInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookIdInputFieldKeyPressed(evt);
            }
        });

        titleInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleInputFieldKeyPressed(evt);
            }
        });

        authorInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                authorInputFieldKeyPressed(evt);
            }
        });

        publicDateInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                publicDateInputFieldKeyPressed(evt);
            }
        });

        categoryInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                categoryInputFieldKeyPressed(evt);
            }
        });

        bookIdLabel.setText("id");

        titleLabel.setText("title");

        authorLabel.setText("author");

        publicDateLabel.setText("public date");

        categoryLabel.setText("category");

        enterBookButton.setText("enter");
        enterBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBookButtonActionPerformed(evt);
            }
        });

        saveBookButton.setText("save");
        saveBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBookButtonActionPerformed(evt);
            }
        });

        closeFormButton.setText("close");
        closeFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormButtonActionPerformed(evt);
            }
        });

        messageField.setEditable(false);
        messageField.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterBookButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveBookButton)
                        .addGap(18, 18, 18)
                        .addComponent(closeFormButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(publicDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookIdInputField)
                            .addComponent(titleInputField)
                            .addComponent(authorInputField)
                            .addComponent(publicDateInputField)
                            .addComponent(categoryInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(messageField))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookIdInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicDateInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publicDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterBookButton)
                    .addComponent(saveBookButton)
                    .addComponent(closeFormButton))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookIdInputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIdInputFieldKeyPressed
        // jump to next input field when press enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            titleInputField.requestFocus();
        }
    }//GEN-LAST:event_bookIdInputFieldKeyPressed

    private void titleInputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleInputFieldKeyPressed
        // jump to next input field when press enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            authorInputField.requestFocus();
        }
    }//GEN-LAST:event_titleInputFieldKeyPressed

    private void authorInputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorInputFieldKeyPressed
        // jump to next input field when press enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            publicDateInputField.requestFocus();
        }
    }//GEN-LAST:event_authorInputFieldKeyPressed

    private void publicDateInputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publicDateInputFieldKeyPressed
        // jump to next input field when press enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            categoryInputField.requestFocus();
        }
    }//GEN-LAST:event_publicDateInputFieldKeyPressed

    private void categoryInputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoryInputFieldKeyPressed
        // jump to next input field when press enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            saveBookButton.doClick();
        }
    }//GEN-LAST:event_categoryInputFieldKeyPressed

    private void enterBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBookButtonActionPerformed
        // clear input field
        bookIdInputField.setText("");
        titleInputField.setText("");
        authorInputField.setText("");
        publicDateInputField.setText("");
        categoryInputField.setText("");
        
    }//GEN-LAST:event_enterBookButtonActionPerformed

    private void saveBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBookButtonActionPerformed
        // get data from input field
        String bookId = bookIdInputField.getText();
        String title = titleInputField.getText();
        String author = authorInputField.getText();
        String publicDate = publicDateInputField.getText();
        String category = categoryInputField.getText();
        
        // request controller to save book
        int result = EnterBookController.enterBook(bookId, title, author, publicDate, category);
        // display message
        messageField.setText(EnterBookController.errorMessages(result));

    }//GEN-LAST:event_saveBookButtonActionPerformed

    private void closeFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormButtonActionPerformed
        // close form
        this.dispose();
    }//GEN-LAST:event_closeFormButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorInputField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField bookIdInputField;
    private javax.swing.JLabel bookIdLabel;
    private javax.swing.JTextField categoryInputField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton closeFormButton;
    private javax.swing.JButton enterBookButton;
    private javax.swing.JTextField messageField;
    private javax.swing.JTextField publicDateInputField;
    private javax.swing.JLabel publicDateLabel;
    private javax.swing.JButton saveBookButton;
    private javax.swing.JTextField titleInputField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
