/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kma.bookmanangement.ui;

import java.util.List;

import com.kma.bookmanangement.controller.ListBookController;


/**
 *
 * @author lxsgo
 */
public class ListBookForm extends javax.swing.JFrame {

    /**
     * Creates new form ListBookForm
     */
    public ListBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorTextField = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        publicDateTextForm = new javax.swing.JTextField();
        CategoryTextField = new javax.swing.JTextField();
        showBookButton = new javax.swing.JButton();
        closeFormButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookListList = new javax.swing.JList<>();
        authorLabel = new javax.swing.JLabel();
        titleLable = new javax.swing.JLabel();
        publicDateLable = new javax.swing.JLabel();
        categoryLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        authorTextField.setEditable(false);
        authorTextField.setBackground(new java.awt.Color(250, 250, 250));


        titleTextField.setEditable(false);
        titleTextField.setBackground(new java.awt.Color(250, 250, 250));

        publicDateTextForm.setEditable(false);
        publicDateTextForm.setBackground(new java.awt.Color(250, 250, 250));

        CategoryTextField.setEditable(false);
        CategoryTextField.setBackground(new java.awt.Color(250, 250, 250));

        showBookButton.setText("show");
        showBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBookButtonActionPerformed(evt);
            }
        });

        closeFormButton.setText("close");
        closeFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormButtonActionPerformed(evt);
            }
        });

        bookListList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bookListListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(bookListList);

        authorLabel.setText("author");

        titleLable.setText("title");

        publicDateLable.setText("public date");

        categoryLable.setText("category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showBookButton)
                .addGap(18, 18, 18)
                .addComponent(closeFormButton)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publicDateTextForm, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLabel)
                    .addComponent(titleLable)
                    .addComponent(publicDateLable)
                    .addComponent(categoryLable))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(publicDateLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(publicDateTextForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeFormButton)
                    .addComponent(showBookButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void closeFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormButtonActionPerformed
        // close form
        this.dispose();
    }//GEN-LAST:event_closeFormButtonActionPerformed

    private void showBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBookButtonActionPerformed
        // request for available ids
        List<String> availableIds = ListBookController.getAvailableBookIds();
        // show available ids
        bookListList.setListData(availableIds.toArray(new String[0]));

    }//GEN-LAST:event_showBookButtonActionPerformed

    private void bookListListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bookListListValueChanged
        // print selected book
        if (!evt.getValueIsAdjusting()) {
            String selectedBookId = bookListList.getSelectedValue();
            // request for book info
            List<String> bookInfo = ListBookController.getBookDataById(selectedBookId);
            // show book info
            authorTextField.setText(bookInfo.get(1));
            titleTextField.setText(bookInfo.get(2));
            publicDateTextForm.setText(bookInfo.get(3));
            CategoryTextField.setText(bookInfo.get(4));

        }
    }//GEN-LAST:event_bookListListValueChanged


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CategoryTextField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JList<String> bookListList;
    private javax.swing.JLabel categoryLable;
    private javax.swing.JButton closeFormButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel publicDateLable;
    private javax.swing.JTextField publicDateTextForm;
    private javax.swing.JButton showBookButton;
    private javax.swing.JLabel titleLable;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
